- name: PostgreSQL | Make sure the postgres data directory exists
  file:
    path: "{{ postgresql_data_directory }}"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    state: directory
    mode: 0700

- name: PostgreSQL | Reset the cluster - drop the existing one
  shell: pg_dropcluster --stop {{ postgresql_version }} {{ postgresql_cluster_name }}
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  when: postgresql_cluster_reset

- name: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale)
  shell: pg_createcluster --start --locale {{ postgresql_locale }} -e {{ postgresql_encoding }} -d {{ postgresql_data_directory }} {{ postgresql_version }} {{ postgresql_cluster_name }}
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  when: postgresql_cluster_reset

- name: PostgreSQL | Update configuration
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgresql_conf_directory }}/{{ item }}"
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0640
  register: postgresql_configuration
  notify: Restart PostgreSQL
  with_items:
    - "pg_hba.conf"
    - "postgresql.conf"

- name: PostgreSQL | Create folder for additional configuration files
  sudo: yes
  sudo_user: "{{ postgresql_admin_user }}"
  file:
    name: "{{ postgresql_conf_directory }}/conf.d"
    state: directory
    owner: "{{ postgresql_admin_user }}"
    group: "{{ postgresql_admin_user }}"
    mode: 0755