- name: Enable overcommit in sysctl
  sysctl:
    name=vm.overcommit_memory
    value=1
    state=present
    reload=yes
    ignoreerrors=yes

- name: Set redis to start at boot
  service:
    name=redis-server
    enabled=yes

- name: Create redis config file
  template:
    src=redis.conf.j2
    dest=/etc/redis/redis.conf
  notify: Restart redis
