- name: Ensure Elasticsearch apt signing key is installed
  apt_key:
    url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present

- name: Ensure Logstash 1.4.x repository is installed
  apt_repository:
    repo="deb http://packages.elasticsearch.org/logstash/1.4/debian stable main"
    update_cache=yes

- name: Ensure logstash is installed
  apt:
    pkg=logstash
    state=installed
