- name: Ensure pip is installed in the server environment
  sudo: yes
  apt: pkg=python-pip state=latest

- name: Ensure virtualenv is installed in the server environment
  sudo: yes
  apt: pkg=python-virtualenv state=latest

- name: Upgrade pip to latest version from PyPI
  sudo: yes
  pip: name=pip extra_args="--upgrade"

- name: Upgrade setuptools to latest version from PyPI
  sudo: yes
  pip: name=setuptools extra_args="--upgrade"
