- name: Install supervisor
  apt:
    name="supervisor{% if supervisor_version is defined %}={{ supervisor_version }}{% endif %}"
    state="{% if supervisor_version is defined %}present{% else %}latest{% endif %}"
