redis_user: redis
redis_dir: /var/lib/redis
redis_nofile_limit: 16384

redis_bind: 0.0.0.0
redis_port: 6379
redis_password: false
redis_tcp_keepalive: 0
redis_maxclients: 10000
redis_timeout: 0
redis_pidfile: "/var/run/redis/redis-server.pid"

redis_slaveof: false
redis_slave_read_only: "yes"
redis_slave_priority: 100
redis_repl_backlog_size: false

redis_logfile: '""'
redis_syslog_enabled: "yes"
redis_syslog_ident: redis_{{ redis_port }}
redis_syslog_facility: USER
redis_loglevel: notice
redis_slowlog_log_slower_than: 10000
redis_slowlog_max_len: 128

redis_databases: 16
redis_maxmemory: false
redis_maxmemory_policy: noeviction
redis_rename_commands: []

redis_save:
  - 900 1
  - 300 10
  - 60 10000
