- name: Ensure configuration file is in place
  template:
    src=elasticsearch.yml.j2
    dest="{{ elasticsearch_conf_dir }}/elasticsearch.yml"
    owner="{{ elasticsearch_user }}"
    group="{{ elasticsearch_group }}"
    mode=0644
  notify:
    - Restart Elasticsearch

- name: Ensure default daemon options are in place
  template:
    src=elasticsearch.default.j2
    dest=/etc/default/elasticsearch
    owner="{{ elasticsearch_user }}"
    group="{{ elasticsearch_group }}"
    mode=0644
  notify:
    - Restart Elasticsearch

- name: Enable Elasticsearch server
  service:
    name=elasticsearch
    enabled=yes
    state=started
